var qt = [
    "Everything in life is luck.",
    "Don't cry for money, it never cries for you.",
    "History may not repeat itself, but it does rhyme.",
    "Hard work beats talent when talent fails to work hard.",
    "If you want to test a man's character, give him power.",
    "The more you sweat in peace, the less you bleed in war.",
    "Give a man a mask and he'll become his true self.",
    "You cannot repress anger or love, or avoid feeling them, and you should not try.",
    "Nothing is more costly than something given free of charge.",
    "The mind must be master of the body.",
    "We're here to put a dent in the universe, otherwise why even be here?",
    "If I have seen further than others, it is by standing upon the shoulders of giants.",
    "Good artists copy, great artists steal.",
    "There is no great genius without some touch of madness.",
    "Boards don't hit back.",
    "Showing off is the fool's idea of glory.",
    "They'll kick you, then they beat you, then they'll tell you it's fair. So beat it!",
    "It's lonely at the top, but, God, I love that lonely feeling.",
    "Still waters run deep.",
    "It's the quiet ones, you have to worry  about.",
    "Forgive, O Lord, my little jokes on Thee And I'll forgive Thy great big one on me.",
    "It doesn't take a rocket scientist to hack into a rocket scientist's computer.",
    "Sometimes it is the people no one can imagine anything of who do the things no one can imagine.",
    "Silent people have the loudest minds.",
    "Cowards die many times before their actual deaths.",
    "After two weeks of working on a project, you know whether it will work or not."
];

var auth = [
    "Donald Trump",
    "Kevin O'Leary",
    "Mark Twain",
    "Kevin Durant",
    "Abraham Lincoln",
    "Norman Schwarzkopf",
    "Joker",
    "Robert Greene",
    "Michihiro Matsumoto",
    "Johnny English",
    "Steve Jobs",
    "Isaac Newton",
    "Pablo Picasso",
    "Aristotle",
    "Enter the Dragon",
    "Bruce Lee",
    "Michael Jackson",
    "Elvis Presley",
    "Latin Proverb",
    "Unknown",
    "Robert Frost",
    "Internet",
    "Alan Turing",
    "Stephen Hawking",
    "Julius Caesar",
    "Bill Budge"
];